version: '3.8'
services:
  postgres:
    image: postgres:13.4
    restart: always
    ports:
      - "5554:5432"
    environment:
      POSTGRES_USER: tripuser
      POSTGRES_PASSWORD: trippass
      POSTGRES_DB: tripmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 